/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    Drag: typeof import('./../../src/components/drag/index.vue')['default']
    DragDraggableResizable: typeof import('./../../src/components/drag/DraggableResizable.vue')['default']
    InfiniteList: typeof import('./../../src/components/infinite-list/index.vue')['default']
    InfiniteListAnimation: typeof import('./../../src/components/infinite-list/Animation.vue')['default']
    InfiniteListComputed: typeof import('./../../src/components/infinite-list/Computed.vue')['default']
    InfiniteListDemo: typeof import('./../../src/components/infinite-list/demo.vue')['default']
    InfiniteListHorizonal: typeof import('./../../src/components/infinite-list/horizonal.vue')['default']
    InfiniteListHorizonalCopy: typeof import('./../../src/components/infinite-list/horizonalCopy.vue')['default']
    InfiniteListIntersectionObserver: typeof import('./../../src/components/infinite-list/IntersectionObserver.vue')['default']
    InfiniteListOrderBook: typeof import('./../../src/components/infinite-list/OrderBook.vue')['default']
    InfiniteListOrderBookCopy: typeof import('./../../src/components/infinite-list/OrderBookCopy.vue')['default']
    InfiniteListSwiper: typeof import('./../../src/components/infinite-list/Swiper.vue')['default']
    InfiniteListTest: typeof import('./../../src/components/infinite-list/test.vue')['default']
    InfiniteListVirtualSocketList: typeof import('./../../src/components/infinite-list/VirtualSocketList.vue')['default']
    Layout: typeof import('./../../src/components/layout/index.vue')['default']
    LayoutCompSub1: typeof import('./../../src/components/layout/compSub1.vue')['default']
    LayoutCompSub2: typeof import('./../../src/components/layout/compSub2.vue')['default']
    LayoutCustomScrollbar: typeof import('./../../src/components/layout/CustomScrollbar.vue')['default']
    LayoutDraggableResizable: typeof import('./../../src/components/layout/DraggableResizable.vue')['default']
    LayoutDragResizeContainer: typeof import('./../../src/components/layout/dragResizeContainer.vue')['default']
    LayoutExchangeChart: typeof import('./../../src/components/layout/ExchangeChart.vue')['default']
    LayoutExchangeInfo: typeof import('./../../src/components/layout/ExchangeInfo.vue')['default']
    LayoutExchangeList: typeof import('./../../src/components/layout/ExchangeList.vue')['default']
    LayoutHeader: typeof import('./../../src/components/layout/Header.vue')['default']
    LayoutUserExchangeTable: typeof import('./../../src/components/layout/UserExchangeTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewTransition: typeof import('./../../src/components/view-transition/index.vue')['default']
  }
}
