/*
 * @Author: 田鑫
 * @Date: 2024-08-12 15:10:19
 * @LastEditors: 田鑫
 * @LastEditTime: 2024-08-12 16:35:56
 * @Description:
 */

export const coinGroup = [
	[
		{
			id: 1,
			name: "USDT",
			fullName: "Tether",
			precision: 6,
			logo: "https://ucc-local.oss-ap-southeast-1.aliyuncs.com/%E5%B8%81%E7%A7%8Dlogo/%E5%B8%81%E7%A7%8Dlogo/USDT.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 4,
			isHot: 1,
		},
		{
			id: 2,
			name: "BTC",
			fullName: "Bitcoin",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/761461.png",
			track: "POW",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 1,
			isHot: 1,
		},
		{
			id: 15,
			name: "BNB",
			fullName: "BNB",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/BNB.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 13,
			isHot: 0,
		},
		{
			id: 33,
			name: "SHIB",
			fullName: "Shiba Inu",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/383211.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 24,
			isHot: 0,
		},
		{
			id: 42,
			name: "ENJ",
			fullName: "Enjin Coin",
			precision: 4,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/enj.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 0,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 12,
			isHot: 0,
		},
		{
			id: 49,
			name: "USDC",
			fullName: "USD Coin",
			precision: 4,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/USDC.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: "1000000",
			sort: 4,
			isHot: 0,
		},
		{
			id: 58,
			name: "CHZ",
			fullName: "Chiliz",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116115902622.png",
			track: "Fan Token",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 11,
			isHot: 0,
		},
		{
			id: 64,
			name: "WBTC",
			fullName: "Wrapped BTC",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/545002.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 67,
			isHot: 0,
		},
		{
			id: 68,
			name: "SNX",
			fullName: "Synthetix",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/790024.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 31,
			isHot: 0,
		},
		{
			id: 73,
			name: "QNT",
			fullName: "Quant",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/478893.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 31,
			isHot: 0,
		},
		{
			id: 78,
			name: "SLP",
			fullName: "Smooth Love Potion",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/870155.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 43,
			isHot: 0,
		},
		{
			id: 83,
			name: "IQ",
			fullName: "IQ",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116112445746.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 47,
			isHot: 0,
		},
		{
			id: 87,
			name: "ENS",
			fullName: "Ethereum Name Service",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/175035.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 53,
			isHot: 0,
		},
		{
			id: 91,
			name: "COMP",
			fullName: "Compound",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/998858.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 53,
			isHot: 0,
		},
		{
			id: 95,
			name: "NFT",
			fullName: "APENFT",
			precision: 6,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/482232.png",
			track: "NFT",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 58,
			isHot: 0,
		},
		{
			id: 99,
			name: "CEEK",
			fullName: "CEEK VR",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/845032.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 30,
			isHot: 0,
		},
		{
			id: 103,
			name: "GRT",
			fullName: "The Graph",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/824569.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 70,
			isHot: 0,
		},
		{
			id: 107,
			name: "IMX",
			fullName: "ImmutableX",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/577805.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 68,
			isHot: 0,
		},
		{
			id: 111,
			name: "NEAR",
			fullName: "NEAR Protocol",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/545926.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 35,
			isHot: 0,
		},
		{
			id: 115,
			name: "DENT",
			fullName: "Dent",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/502137.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 50,
			isHot: 0,
		},
		{
			id: 120,
			name: "VGX",
			fullName: "Voyager Token",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116124351225.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 56,
			isHot: 0,
		},
		{
			id: 126,
			name: "JASMY",
			fullName: "JasmyCoin",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116120151530.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 65,
			isHot: 0,
		},
		{
			id: 130,
			name: "MBOX",
			fullName: "MOBOX",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230129101702859.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 143,
			name: "AGIX",
			fullName: "SingularityNET",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230201165336325.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 147,
			name: "BSW",
			fullName: "Biswap",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/435937.jpeg",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 153,
			name: "COTI",
			fullName: "COTI",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/234397.jpeg",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 159,
			name: "LDO",
			fullName: "Lido DAO",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/654995.jpeg",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 164,
			name: "AUDIO",
			fullName: "Audius",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/786845.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 170,
			name: "ID",
			fullName: "SPACE ID",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/651502.jpeg",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 175,
			name: "CHESS",
			fullName: "Tranchess",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/653114.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 183,
			name: "VET",
			fullName: "VeChain",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/113382.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 193,
			name: "OZON",
			fullName: "OZON",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/40731.jpg",
			track: "Gaming",
			isOpen: 0,
			isShow: 1,
			depositOpen: 0,
			withdrawOpen: 0,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 100,
			isHot: 0,
		},
		{
			id: 200,
			name: "XAUT",
			fullName: "Tether Gold",
			precision: 6,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/953961.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0.001",
			withdrawMax: "10",
			sort: 20,
			isHot: 0,
		},
		{
			id: 204,
			name: "EDU",
			fullName: "Open Campus",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/740238.png",
			track: "Innovation",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "5",
			withdrawMax: "100000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 209,
			name: "MEME",
			fullName: "Memecoin",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/399908.png",
			track: "Fan Token",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1125",
			withdrawMax: "50000000",
			sort: 15,
			isHot: 0,
		},
		{
			id: 214,
			name: "ALT",
			fullName: "Altlayer",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/669554.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "10",
			withdrawMax: "250000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 218,
			name: "PYTH",
			fullName: "Pyth Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/670265.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "10",
			withdrawMax: "200000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 222,
			name: "C98",
			fullName: "Coin98",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/174281.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "3000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 270,
			name: "PERP",
			fullName: "Perpetual Protocol",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/957403.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 0,
			withdrawMin: "1",
			withdrawMax: "1000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 307,
			name: "CULO",
			fullName: "CULO",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/164996.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 50,
			isHot: 0,
		},
		{
			id: 314,
			name: "GAU",
			fullName: "Gamer Arena",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/300907.png",
			track: "GameFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "10",
			withdrawMax: "100000000",
			sort: 50,
			isHot: 0,
		},
		{
			id: 318,
			name: "AEVO",
			fullName: "Aevo",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/656498.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "500000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 335,
			name: "ACH",
			fullName: "Alchemy Pay",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/623398.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "50",
			withdrawMax: "30000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 339,
			name: "PRIME",
			fullName: "Echelon Prime",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/192413.png",
			track: "GameFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0.1",
			withdrawMax: "600000",
			sort: 40,
			isHot: 0,
		},
		{
			id: 345,
			name: "ZEUS",
			fullName: "Zeus Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/432576.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "500000",
			sort: 30,
			isHot: 0,
		},
		{
			id: 349,
			name: "MAVIA",
			fullName: "Heroes of Mavia",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/885626.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0.3",
			withdrawMax: "29303",
			sort: 30,
			isHot: 0,
		},
		{
			id: 355,
			name: "RARE",
			fullName: "SuperRare",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/581202.png",
			track: "NFT",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "8",
			withdrawMax: "800000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 363,
			name: "BICO",
			fullName: "Biconomy",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/112914.png",
			track: "Innovation",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 0,
			withdrawMin: "2",
			withdrawMax: "1879984",
			sort: 20,
			isHot: 0,
		},
	],
	[
		{
			id: 3,
			name: "ETH",
			fullName: "Ethereum",
			precision: 8,
			logo: "https://ucc-local.oss-ap-southeast-1.aliyuncs.com/%E5%B8%81%E7%A7%8Dlogo/%E5%B8%81%E7%A7%8Dlogo/eth.png",
			track: "Metaverse",
			isOpen: 0,
			isShow: 1,
			depositOpen: 0,
			withdrawOpen: 0,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 2,
			isHot: 0,
		},
		{
			id: 4,
			name: "LTC",
			fullName: "Litecoin",
			precision: 8,
			logo: "https://ucc-local.oss-ap-southeast-1.aliyuncs.com/%E5%B8%81%E7%A7%8Dlogo/%E5%B8%81%E7%A7%8Dlogo/LTC.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 0,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 6,
			isHot: 0,
		},
		{
			id: 19,
			name: "SNT",
			fullName: "Status",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116131201938.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "30",
			withdrawMax: "300000000",
			sort: 17,
			isHot: 0,
		},
		{
			id: 36,
			name: "DOGE",
			fullName: "Dogecoin",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/Doge.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "20",
			withdrawMax: null,
			sort: 8,
			isHot: 0,
		},
		{
			id: 43,
			name: "AXS",
			fullName: "Axie Infinity",
			precision: 2,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/961337.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 13,
			isHot: 0,
		},
		{
			id: 54,
			name: "DAI",
			fullName: "Dai",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/DAI.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 9,
			isHot: 0,
		},
		{
			id: 59,
			name: "APE",
			fullName: "ApeCoin",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/55719.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 20,
			isHot: 0,
		},
		{
			id: 65,
			name: "CRO",
			fullName: "Cronos",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/444026.png",
			track: "POS",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 27,
			isHot: 0,
		},
		{
			id: 70,
			name: "GMT",
			fullName: "STEPN",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/351207.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 32,
			isHot: 0,
		},
		{
			id: 74,
			name: "DYDX",
			fullName: "dYdX",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116104354915.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 62,
			isHot: 0,
		},
		{
			id: 79,
			name: "1INCH",
			fullName: "1inch Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/832430.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 44,
			isHot: 0,
		},
		{
			id: 84,
			name: "SRM",
			fullName: "Serum",
			precision: 6,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/424547.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 0,
			withdrawOpen: 0,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 53,
			isHot: 0,
		},
		{
			id: 88,
			name: "JST",
			fullName: "Just",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/955489.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 50,
			isHot: 0,
		},
		{
			id: 92,
			name: "MKR",
			fullName: "Maker",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/510570.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 54,
			isHot: 0,
		},
		{
			id: 96,
			name: "HFT",
			fullName: "Hashflow",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/987017.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 59,
			isHot: 0,
		},
		{
			id: 100,
			name: "XTZ",
			fullName: "Tezos",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/257158.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 64,
			isHot: 0,
		},
		{
			id: 104,
			name: "ONT",
			fullName: "Ontology",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/545964.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 32,
			isHot: 0,
		},
		{
			id: 108,
			name: "FXS",
			fullName: "Frax Share",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/109142.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 33,
			isHot: 0,
		},
		{
			id: 112,
			name: "CAKE",
			fullName: "PancakeSwap",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/777170.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 37,
			isHot: 0,
		},
		{
			id: 116,
			name: "PYR",
			fullName: "Vulcan Forged PYR",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/535946.png",
			track: "NFT",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 69,
			isHot: 0,
		},
		{
			id: 122,
			name: "LPT",
			fullName: "Livepeer",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/353283.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 61,
			isHot: 0,
		},
		{
			id: 127,
			name: "OCEAN",
			fullName: "Ocean Protocol",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/825255.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 66,
			isHot: 0,
		},
		{
			id: 133,
			name: "RSR",
			fullName: "Reserve Rights",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/10763.jpeg",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 144,
			name: "RLC",
			fullName: "iExec RLC",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230201165922392.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 149,
			name: "CELR",
			fullName: "Celer Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/962745.jpeg",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 154,
			name: "GFT",
			fullName: "Gifto",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/632394.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 160,
			name: "CFX",
			fullName: "Conflux",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/934343.jpeg",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 166,
			name: "HIGH",
			fullName: "Highstreet",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/872282.jpeg",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 171,
			name: "ARB",
			fullName: "Arbitrum",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/880602.jpeg",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 176,
			name: "RDNT",
			fullName: "Radiant Capital",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/790934.jpeg",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 184,
			name: "WLD",
			fullName: "Worldcoin",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/966407.jpg",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 6,
			isHot: 1,
		},
		{
			id: 194,
			name: "CYBER",
			fullName: "CyberConnect",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/150529.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "20000",
			sort: 10,
			isHot: 0,
		},
		{
			id: 201,
			name: "EURT",
			fullName: "Tether EURt",
			precision: 6,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/223391.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "100000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 205,
			name: "OGN",
			fullName: "Origin Protocol",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/577401.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "20",
			withdrawMax: "1000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 210,
			name: "XAI",
			fullName: "Xai",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/370291.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "2.2",
			withdrawMax: "100000",
			sort: 10,
			isHot: 0,
		},
		{
			id: 215,
			name: "JTO",
			fullName: "Jito",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/37731.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "2",
			withdrawMax: "50000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 219,
			name: "PENDLE",
			fullName: "Pendle",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/223055.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "2",
			withdrawMax: "300000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 223,
			name: "FRONT",
			fullName: "Frontier",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/288134.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "2",
			withdrawMax: "2000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 278,
			name: "BEAM",
			fullName: "Beam",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/795425.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 0,
			withdrawMin: "30",
			withdrawMax: "30000000",
			sort: 40,
			isHot: 0,
		},
		{
			id: 308,
			name: "BRETT",
			fullName: "Brett",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/759602.png",
			track: "Fan Token",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 20,
			isHot: 0,
		},
		{
			id: 315,
			name: "ETHFI",
			fullName: "ether.fi",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/417649.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "200000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 320,
			name: "TON",
			fullName: "Toncoin",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/941630.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0.5",
			withdrawMax: "200000",
			sort: 10,
			isHot: 0,
		},
		{
			id: 336,
			name: "FLUX",
			fullName: "FLUX",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/939467.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "1000000",
			sort: 30,
			isHot: 0,
		},
		{
			id: 340,
			name: "PNG",
			fullName: "Pangolin",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/155935.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "3",
			withdrawMax: "3000000",
			sort: 40,
			isHot: 0,
		},
		{
			id: 346,
			name: "FYN",
			fullName: "Affyn",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/43241.png",
			track: "GameFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "20",
			withdrawMax: "25000000",
			sort: 50,
			isHot: 0,
		},
		{
			id: 350,
			name: "RIO",
			fullName: "Realio Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/502349.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "612585",
			sort: 30,
			isHot: 0,
		},
		{
			id: 357,
			name: "BUBBLE",
			fullName: "Bubble",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/651898.png",
			track: "GameFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "10000000",
			sort: 50,
			isHot: 0,
		},
		{
			id: 377,
			name: "CAW",
			fullName: "CAW",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/323387.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 1,
			isHot: 0,
		},
	],
	[
		{
			id: 8,
			name: "TRX",
			fullName: "TRON",
			precision: 6,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/439733.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 7,
			isHot: 0,
		},
		{
			id: 11,
			name: "LINK",
			fullName: "Chainlink",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/LINK.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 27,
			name: "XRP",
			fullName: "XRP",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/XRP.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 4,
			isHot: 0,
		},
		{
			id: 38,
			name: "MANA",
			fullName: "Decentraland",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/MANA.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 47,
			name: "CRV",
			fullName: "Curve DAO Token",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/932654.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 25,
			isHot: 0,
		},
		{
			id: 55,
			name: "MASK",
			fullName: "Mask Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/700409.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 18,
			isHot: 0,
		},
		{
			id: 61,
			name: "ATOM",
			fullName: "Cosmos",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/797704.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 22,
			isHot: 0,
		},
		{
			id: 66,
			name: "BAL",
			fullName: "Balancer",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/929167.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 28,
			isHot: 0,
		},
		{
			id: 71,
			name: "AAVE",
			fullName: "Aave",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/11857.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 40,
			isHot: 0,
		},
		{
			id: 76,
			name: "SOL",
			fullName: "Solana",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/SOL-Solana.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 6,
			isHot: 0,
		},
		{
			id: 80,
			name: "KNC",
			fullName: "Kyber Network Crystal v2",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/99567.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 45,
			isHot: 0,
		},
		{
			id: 85,
			name: "SPELL",
			fullName: "Spell Token",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/446070.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 48,
			isHot: 0,
		},
		{
			id: 89,
			name: "EGLD",
			fullName: "MultiversX",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/584235.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "20000",
			sort: 52,
			isHot: 0,
		},
		{
			id: 93,
			name: "ANT",
			fullName: "Aragon",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/970036.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 55,
			isHot: 0,
		},
		{
			id: 97,
			name: "REEF",
			fullName: "Reef",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/464877.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 60,
			isHot: 0,
		},
		{
			id: 101,
			name: "HOT",
			fullName: "Holo",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/710163.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 8,
			isHot: 0,
		},
		{
			id: 105,
			name: "OKB",
			fullName: "OKB",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116125626082.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 71,
			isHot: 0,
		},
		{
			id: 109,
			name: "NEXO",
			fullName: "Nexo",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/296662.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 34,
			isHot: 0,
		},
		{
			id: 113,
			name: "LUNC",
			fullName: "Terra Classic",
			precision: 6,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116125524612.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 0,
			withdrawOpen: 0,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 38,
			isHot: 0,
		},
		{
			id: 117,
			name: "STORJ",
			fullName: "Storj",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/300136.png",
			track: "Storage",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 72,
			isHot: 0,
		},
		{
			id: 123,
			name: "CVX",
			fullName: "Convex Finance",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/974205.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 57,
			isHot: 0,
		},
		{
			id: 128,
			name: "FET",
			fullName: "Fetch.AI",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/715045.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 20,
			isHot: 0,
		},
		{
			id: 135,
			name: "LOOKS",
			fullName: "LooksRare",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230129163819553.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 145,
			name: "GAL",
			fullName: "Galxe",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/795875.png",
			track: "NFT",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 150,
			name: "API3",
			fullName: "API3",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/224476.jpeg",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 156,
			name: "BLUR",
			fullName: "BLUR",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/604056.jpeg",
			track: "NFT",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 161,
			name: "SSV",
			fullName: "ssv.network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/605046.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 167,
			name: "GLM",
			fullName: "Golem",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/162184.jpeg",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 173,
			name: "JOE",
			fullName: "JOE",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/444391.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 177,
			name: "PEPE",
			fullName: "Pepe",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/48250.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 5,
			isHot: 0,
		},
		{
			id: 185,
			name: "OP",
			fullName: "Optimism",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/572797.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 196,
			name: "TRB",
			fullName: "Tellor",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/760486.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0.1",
			withdrawMax: "2000",
			sort: 10,
			isHot: 0,
		},
		{
			id: 202,
			name: "CUAN",
			fullName: "CuanSwap",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/949643.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "100",
			withdrawMax: "10000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 206,
			name: "CTSI",
			fullName: "Cartesi",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/697567.png",
			track: "POS",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "25",
			withdrawMax: "2500000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 211,
			name: "MAV",
			fullName: "Maverick Protocol",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/6758.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "2",
			withdrawMax: "1000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 216,
			name: "JUP",
			fullName: "Jupiter",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/213391.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "1000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 220,
			name: "SATS",
			fullName: "SATS",
			precision: 12,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/29405.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1000000",
			withdrawMax: "100000000000",
			sort: 15,
			isHot: 0,
		},
		{
			id: 230,
			name: "ALICE",
			fullName: "MyNeighborAlice",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/308374.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "1000000",
			sort: 30,
			isHot: 0,
		},
		{
			id: 301,
			name: "PORTAL",
			fullName: "Portal",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/16731.jpg",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "100000",
			sort: 15,
			isHot: 0,
		},
		{
			id: 309,
			name: "WIF",
			fullName: "dogwifhat",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/396405.png",
			track: "Fan Token",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 0,
			withdrawMin: "1",
			withdrawMax: "5000000",
			sort: 30,
			isHot: 0,
		},
		{
			id: 316,
			name: "W",
			fullName: "Wormhole",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/899293.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "2",
			withdrawMax: "10000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 323,
			name: "OMNI",
			fullName: "Omni Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/954018.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "1000000",
			sort: 30,
			isHot: 0,
		},
		{
			id: 337,
			name: "REZ",
			fullName: "Renzo",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/982348.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "1000000",
			sort: 50,
			isHot: 0,
		},
		{
			id: 342,
			name: "TLM",
			fullName: "Alien Worlds",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/48548.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 0,
			withdrawMin: "1",
			withdrawMax: "500000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 347,
			name: "AGI",
			fullName: "Delysium",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/59891.jpg",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "3",
			withdrawMax: "3000000",
			sort: 100,
			isHot: 0,
		},
		{
			id: 351,
			name: "VTHO",
			fullName: "VeThor Token",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/719977.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 0,
			withdrawOpen: 0,
			withdrawMin: "317",
			withdrawMax: "31662090",
			sort: 10,
			isHot: 0,
		},
		{
			id: 359,
			name: "NOS",
			fullName: "Nosana",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/623214.png",
			track: "Innovation",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0.5",
			withdrawMax: "20000000",
			sort: 100,
			isHot: 0,
		},
		{
			id: 378,
			name: "COQ",
			fullName: "Coq Inu",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/612383.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 0,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 1,
			isHot: 0,
		},
	],
	[
		{
			id: 12,
			name: "YFI",
			fullName: "yearn.finance",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/343115.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 9,
			isHot: 0,
		},
		{
			id: 13,
			name: "UNI",
			fullName: "Uniswap",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/Uni.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 11,
			isHot: 0,
		},
		{
			id: 29,
			name: "ADA",
			fullName: "Cardano",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/997494.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "1000000",
			sort: 7,
			isHot: 0,
		},
		{
			id: 39,
			name: "SAND",
			fullName: "The Sandbox",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/SAND.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 48,
			name: "PEOPLE",
			fullName: "ConstitutionDAO",
			precision: 6,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/364915.png",
			track: "Metaverse",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "350",
			withdrawMax: "100000000",
			sort: 16,
			isHot: 0,
		},
		{
			id: 57,
			name: "NMR",
			fullName: "Numeraire",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/579935.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 23,
			isHot: 0,
		},
		{
			id: 63,
			name: "AVAX",
			fullName: "Avalanche",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/306340.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 7,
			isHot: 0,
		},
		{
			id: 67,
			name: "SUSHI",
			fullName: "SushiSwap",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/563132.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 29,
			isHot: 0,
		},
		{
			id: 72,
			name: "FLOW",
			fullName: "Flow",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/450282.png",
			track: "NFT",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 52,
			isHot: 0,
		},
		{
			id: 77,
			name: "ZEC",
			fullName: "Zcash",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/359844.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 42,
			isHot: 0,
		},
		{
			id: 81,
			name: "BAND",
			fullName: "Band Protocol",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/208253.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 46,
			isHot: 0,
		},
		{
			id: 86,
			name: "WIN",
			fullName: "WINkLink",
			precision: 6,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116124124071.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 49,
			isHot: 0,
		},
		{
			id: 90,
			name: "BAT",
			fullName: "Basic Attention Token",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/582907.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 51,
			isHot: 0,
		},
		{
			id: 94,
			name: "BTT",
			fullName: "BitTorrent",
			precision: 9,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/161663.png",
			track: "Storage",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 56,
			isHot: 0,
		},
		{
			id: 98,
			name: "ANKR",
			fullName: "Ankr",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/938980.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 61,
			isHot: 0,
		},
		{
			id: 102,
			name: "RNDR",
			fullName: "Render Token",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230116125642609.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 8,
			isHot: 0,
		},
		{
			id: 106,
			name: "REN",
			fullName: "Ren",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/629319.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 73,
			isHot: 0,
		},
		{
			id: 110,
			name: "INJ",
			fullName: "Injective",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/191523.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 36,
			isHot: 0,
		},
		{
			id: 114,
			name: "LOOM",
			fullName: "Loom Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/263708.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 51,
			isHot: 0,
		},
		{
			id: 119,
			name: "WOO",
			fullName: "WOO Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/275391.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 55,
			isHot: 0,
		},
		{
			id: 124,
			name: "AMP",
			fullName: "Amp",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/852744.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 58,
			isHot: 0,
		},
		{
			id: 129,
			name: "HOOK",
			fullName: "Hooked Protocol",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/746728.png",
			track: "NFT",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 137,
			name: "HEX",
			fullName: "HEX",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/20230129165145163.png",
			track: "",
			isOpen: 1,
			isShow: 1,
			depositOpen: 0,
			withdrawOpen: 0,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 146,
			name: "YGG",
			fullName: "Yield Guild Games",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/52149.jpeg",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 151,
			name: "PHA",
			fullName: "Phala Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/690099.jpeg",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 157,
			name: "DAR",
			fullName: "Mines of Dalarnia",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/868860.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 163,
			name: "LQTY",
			fullName: "Liquity",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/352257.jpeg",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 168,
			name: "DODO",
			fullName: "DODO",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/588282.jpeg",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 174,
			name: "GHST",
			fullName: "Aavegotchi",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/339235.jpeg",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 182,
			name: "MATIC",
			fullName: "Polygon",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/993422.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 3,
			isHot: 0,
		},
		{
			id: 188,
			name: "SUI",
			fullName: "Sui",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/coin/877934.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "1000000",
			sort: 10,
			isHot: 0,
		},
		{
			id: 199,
			name: "BIGTIME",
			fullName: "Big Time",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/612875.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 10,
			isHot: 0,
		},
		{
			id: 203,
			name: "ORDI",
			fullName: "Ordinals",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/204173.png",
			track: "Innovation",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0.08",
			withdrawMax: "1650",
			sort: 5,
			isHot: 0,
		},
		{
			id: 208,
			name: "BONK",
			fullName: "Bonk",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/540922.png",
			track: "Innovation",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "10000000",
			withdrawMax: "10000000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 212,
			name: "AI",
			fullName: "Sleepless AI",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/907222.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "5",
			withdrawMax: "1000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 217,
			name: "MAGIC",
			fullName: "Treasure",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/132774.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "3",
			withdrawMax: "100000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 221,
			name: "PIXEL",
			fullName: "Pixels",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/992894.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "2",
			withdrawMax: "2000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 235,
			name: "FLOKI",
			fullName: "FLOKI",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/896342.png",
			track: "Fan Token",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "10000",
			withdrawMax: "10000000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 306,
			name: "SWCH",
			fullName: "SwissCheese",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/503710.png",
			track: "Gaming",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0",
			withdrawMax: null,
			sort: 40,
			isHot: 0,
		},
		{
			id: 313,
			name: "PUMP",
			fullName: "Big Pump",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/791859.jpg",
			track: "MemeCoin",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "100000",
			withdrawMax: "100000000000",
			sort: 50,
			isHot: 0,
		},
		{
			id: 317,
			name: "ENA",
			fullName: "Ethena",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/297142.png",
			track: "DeFi",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "1000000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 334,
			name: "BVM",
			fullName: "BVM",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/744001.jpg",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "300000",
			sort: 20,
			isHot: 0,
		},
		{
			id: 338,
			name: "AIOZ",
			fullName: "AIOZ Network",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/324649.png",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "2",
			withdrawMax: "200000",
			sort: 30,
			isHot: 0,
		},
		{
			id: 344,
			name: "MEW",
			fullName: "cat in a dogs world",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/848953.png",
			track: "Fan Token",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "1",
			withdrawMax: "500000",
			sort: 30,
			isHot: 0,
		},
		{
			id: 348,
			name: "HNT",
			fullName: "Helium",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/634435.jpg",
			track: "Infrastructure",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "0.1",
			withdrawMax: "500000",
			sort: 50,
			isHot: 0,
		},
		{
			id: 354,
			name: "MERL",
			fullName: "Merlin Chain",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/983132.png",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 1,
			withdrawMin: "2.56",
			withdrawMax: "2566574",
			sort: 30,
			isHot: 0,
		},
		{
			id: 362,
			name: "VANRY",
			fullName: "Vanar Chain",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/354517.jpeg",
			track: "Layer 1/Layer 2",
			isOpen: 1,
			isShow: 1,
			depositOpen: 1,
			withdrawOpen: 0,
			withdrawMin: "6",
			withdrawMax: "5233867",
			sort: 20,
			isHot: 0,
		},
		{
			id: 385,
			name: "TRUMP",
			fullName: "MAGA",
			precision: 8,
			logo: "https://bitunix-public.oss-ap-northeast-1.aliyuncs.com/config/kv/912986.png",
			track: "MemeCoin",
			isOpen: 1,
			isShow: 1,
			depositOpen: 0,
			withdrawOpen: 0,
			withdrawMin: "1",
			withdrawMax: "3000000",
			sort: 100,
			isHot: 0,
		},
	],
];
